export const productColors = [
  "spacegray",
  "silver",
  "gold",
  "blue",
  "red",
  "black",
  "green",
  "yellow",
  "white",
  "purple",
  "midnightgreen",
  "rosegold",
  "coral",
  "midnight",
  "spaceblack",
  "pink",
  "graphite",
  "sierrablue",
  "rose-gold",
  "sky-blue",
  "starlight",
];

export const bgColorMap = {
  spacegray: "bg-gray-700",
  silver: "bg-gray-300",
  gold: "bg-yellow-400",
  blue: "bg-blue-500",
  red: "bg-red-500",
  black: "bg-black",
  green: "bg-green-500",
  yellow: "bg-yellow-300",
  white: "bg-white",
  purple: "bg-purple-500",
  midnightgreen: "bg-teal-900",
  rosegold: "bg-pink-400",
  coral: "bg-orange-400",
  midnight: "bg-indigo-900",
  spaceblack: "bg-gray-900",
  pink: "bg-pink-500",
  graphite: "bg-gray-800",
  sierrablue: "bg-blue-300",
  "rose-gold": "bg-pink-300",
  "sky-blue": "bg-sky-400",
  starlight: "bg-yellow-100",
};
